import { Company, Discussion, UserProfile, ExpertTag, Document, Job, LearningCircle, Event } from "./types";

export const EXPERT_TAGS: ExpertTag[] = [
  { id: "1", name: "Longevity Science", emoji: "🧬", created_at: "" },
  { id: "2", name: "Space Economy", emoji: "🚀", created_at: "" },
  { id: "3", name: "VC/Investing", emoji: "💼", created_at: "" },
  { id: "4", name: "Legal/Regulatory", emoji: "⚖️", created_at: "" },
  { id: "5", name: "Finance/CFO", emoji: "💰", created_at: "" },
  { id: "6", name: "Scientific Research", emoji: "🔬", created_at: "" },
  { id: "7", name: "Operations/Scaling", emoji: "🏗️", created_at: "" },
];

export const MOCK_COMPANIES: Company[] = [
  {
    id: "c1",
    name: "NovaSenescence",
    sector: "longevity",
    stage: "Series A",
    description: "Developing senolytics therapies targeting age-related cellular decline. Their lead compound NS-401 has shown 40% reduction in senescent cell burden in Phase I trials.",
    logo_url: null,
    website: "https://example.com",
    investment_amount: 1500000,
    entry_valuation: 15000000,
    current_valuation: 22500000,
    entry_date: "2024-03-15",
    why_invested: "NovaSenescence represents a best-in-class approach to senolytics with strong IP protection and a seasoned management team from leading pharma backgrounds.",
    employees: 28,
    founded_year: 2021,
    location: "Basel, Switzerland",
    created_at: "",
    updated_at: "",
  },
  {
    id: "c2",
    name: "OrbitMaterials",
    sector: "space",
    stage: "Seed",
    description: "Manufacturing advanced composite materials in microgravity environments. Their orbital foundry produces ultra-pure fiber optics and specialty alloys impossible to create on Earth.",
    logo_url: null,
    website: "https://example.com",
    investment_amount: 800000,
    entry_valuation: 8000000,
    current_valuation: 14000000,
    entry_date: "2024-06-01",
    why_invested: "First-mover advantage in space manufacturing with signed LOIs from three major telecom companies for their ZBLAN fiber optic cables.",
    employees: 15,
    founded_year: 2022,
    location: "Toulouse, France",
    created_at: "",
    updated_at: "",
  },
  {
    id: "c3",
    name: "CryoGenix",
    sector: "longevity",
    stage: "Pre-Seed",
    description: "Pioneering cryopreservation techniques for organ banking. Their vitrification protocol enables long-term storage of transplant organs, potentially eliminating organ shortage deaths.",
    logo_url: null,
    website: "https://example.com",
    investment_amount: 500000,
    entry_valuation: 5000000,
    current_valuation: 7000000,
    entry_date: "2024-09-10",
    why_invested: "Breakthrough vitrification technology with 95% organ viability rate. Strong partnerships with three EU transplant networks.",
    employees: 12,
    founded_year: 2023,
    location: "Munich, Germany",
    created_at: "",
    updated_at: "",
  },
  {
    id: "c4",
    name: "LunarLogistics",
    sector: "space",
    stage: "Series A",
    description: "Building autonomous logistics infrastructure for cislunar operations. Their robotic transfer vehicles (RTVs) enable efficient cargo movement between Earth orbit and the lunar surface.",
    logo_url: null,
    website: "https://example.com",
    investment_amount: 2000000,
    entry_valuation: 25000000,
    current_valuation: 35000000,
    entry_date: "2024-01-20",
    why_invested: "Critical infrastructure play for the growing lunar economy. ESA and NASA contracts already secured for initial missions.",
    employees: 45,
    founded_year: 2020,
    location: "Bremen, Germany",
    created_at: "",
    updated_at: "",
  },
  {
    id: "c5",
    name: "EpigenReset",
    sector: "longevity",
    stage: "Seed",
    description: "Developing epigenetic reprogramming therapies to reverse biological aging. Their platform identifies and modulates key epigenetic markers associated with aging.",
    logo_url: null,
    website: "https://example.com",
    investment_amount: 1200000,
    entry_valuation: 12000000,
    current_valuation: 18000000,
    entry_date: "2024-05-15",
    why_invested: "World-class team from Harvard Wyss Institute. Proprietary epigenetic clock technology with 3 granted patents.",
    employees: 20,
    founded_year: 2022,
    location: "Cambridge, UK",
    created_at: "",
    updated_at: "",
  },
  {
    id: "c6",
    name: "AstroFarm",
    sector: "space",
    stage: "Seed",
    description: "Closed-loop agricultural systems for space habitats. Their bio-regenerative life support systems produce food, recycle water, and generate oxygen for long-duration space missions.",
    logo_url: null,
    website: "https://example.com",
    investment_amount: 700000,
    entry_valuation: 7000000,
    current_valuation: 9000000,
    entry_date: "2024-08-01",
    why_invested: "Essential technology for sustained human presence in space. Dual-use applications for Earth-based vertical farming in extreme environments.",
    employees: 18,
    founded_year: 2023,
    location: "Wageningen, Netherlands",
    created_at: "",
    updated_at: "",
  },
];

export const MOCK_USER: UserProfile = {
  id: "u1",
  full_name: "Alex Reinhardt",
  location: "Luxembourg City",
  bio: "Early-stage investor focused on deeptech and frontier science. Former biotech researcher.",
  linkedin_url: "https://linkedin.com",
  is_profile_public: true,
  open_to_help_with: "Due diligence on biotech companies, scientific advisory",
  investment_committed: 50000,
  created_at: "2024-01-01",
  updated_at: "2024-01-01",
  expert_tags: [EXPERT_TAGS[0], EXPERT_TAGS[2], EXPERT_TAGS[5]],
};

export const MOCK_LPS: UserProfile[] = [
  MOCK_USER,
  {
    id: "u2", full_name: "Maria Kovacs", location: "Vienna, Austria",
    bio: "Space systems engineer with 15 years at ESA. Passionate about commercializing space technology.",
    linkedin_url: null, is_profile_public: true, open_to_help_with: "Space tech evaluation, engineering reviews",
    investment_committed: 25000, created_at: "", updated_at: "",
    expert_tags: [EXPERT_TAGS[1], EXPERT_TAGS[6]],
  },
  {
    id: "u3", full_name: "Thomas Fischer", location: "Zurich, Switzerland",
    bio: "CFO at a mid-cap pharma company. Interested in longevity as both investor and potential beneficiary.",
    linkedin_url: null, is_profile_public: true, open_to_help_with: "Financial modeling, pharma industry connections",
    investment_committed: 100000, created_at: "", updated_at: "",
    expert_tags: [EXPERT_TAGS[0], EXPERT_TAGS[4]],
  },
  {
    id: "u4", full_name: null, location: "Berlin, Germany",
    bio: "Prefer to stay anonymous. Active angel investor.",
    linkedin_url: null, is_profile_public: false, open_to_help_with: null,
    investment_committed: 30000, created_at: "", updated_at: "",
    expert_tags: [EXPERT_TAGS[2]],
  },
  {
    id: "u5", full_name: "Dr. Sophia Chen", location: "Paris, France",
    bio: "Molecular biologist and longevity researcher. Running a lab at Institut Pasteur.",
    linkedin_url: null, is_profile_public: true, open_to_help_with: "Scientific due diligence, research partnerships",
    investment_committed: 15000, created_at: "", updated_at: "",
    expert_tags: [EXPERT_TAGS[0], EXPERT_TAGS[5]],
  },
  {
    id: "u6", full_name: "James O'Sullivan", location: "Dublin, Ireland",
    bio: "Regulatory affairs consultant specializing in EU medical device and pharma regulations.",
    linkedin_url: null, is_profile_public: true, open_to_help_with: "EU regulatory strategy, compliance guidance",
    investment_committed: 20000, created_at: "", updated_at: "",
    expert_tags: [EXPERT_TAGS[3], EXPERT_TAGS[0]],
  },
];

export const MOCK_DISCUSSIONS: Discussion[] = [
  {
    id: "d1", title: "NovaSenescence Phase I Results Discussion",
    content: "Just reviewed the Phase I data from NovaSenescence. The 40% reduction in senescent cell burden is impressive. What are your thoughts on the safety profile and path to Phase II?",
    author_id: "u5", category: "company", company_id: "c1",
    upvotes_count: 12, comments_count: 5, created_at: "2025-03-15T10:00:00Z", updated_at: "2025-03-15T10:00:00Z",
    author: MOCK_LPS[4],
  },
  {
    id: "d2", title: "Longevity Market Outlook 2025",
    content: "The longevity market is projected to reach $600B by 2030. Let's discuss the key trends and how our portfolio is positioned.",
    author_id: "u1", category: "longevity", company_id: null,
    upvotes_count: 8, comments_count: 3, created_at: "2025-03-10T14:00:00Z", updated_at: "2025-03-10T14:00:00Z",
    author: MOCK_USER,
  },
  {
    id: "d3", title: "ESA Artemis Accords Impact on Space Economy",
    content: "With the latest Artemis Accords developments, how do you see this affecting companies like LunarLogistics and OrbitMaterials?",
    author_id: "u2", category: "space", company_id: null,
    upvotes_count: 15, comments_count: 7, created_at: "2025-03-08T09:00:00Z", updated_at: "2025-03-08T09:00:00Z",
    author: MOCK_LPS[1],
  },
  {
    id: "d4", title: "Q4 2024 Portfolio Performance Review",
    content: "Sharing some thoughts on our Q4 performance. Overall portfolio MOIC at 1.4x is strong for a fund this early. Any questions for the next LP call?",
    author_id: "u3", category: "general", company_id: null,
    upvotes_count: 20, comments_count: 11, created_at: "2025-03-01T16:00:00Z", updated_at: "2025-03-01T16:00:00Z",
    author: MOCK_LPS[2],
  },
];

export const MOCK_DOCUMENTS: Document[] = [
  { id: "doc1", title: "Q4 2024 Quarterly Report", category: "quarterly", file_url: "#", file_size: 2500000, company_id: null, uploaded_by: null, created_at: "2025-01-15" },
  { id: "doc2", title: "Q3 2024 Quarterly Report", category: "quarterly", file_url: "#", file_size: 2200000, company_id: null, uploaded_by: null, created_at: "2024-10-15" },
  { id: "doc3", title: "Limited Partnership Agreement", category: "legal", file_url: "#", file_size: 850000, company_id: null, uploaded_by: null, created_at: "2024-01-10" },
  { id: "doc4", title: "Fund Prospectus (ELTIF 2.0)", category: "legal", file_url: "#", file_size: 1200000, company_id: null, uploaded_by: null, created_at: "2024-01-05" },
  { id: "doc5", title: "2024 Tax Certificate", category: "tax", file_url: "#", file_size: 450000, company_id: null, uploaded_by: null, created_at: "2025-02-28" },
  { id: "doc6", title: "NovaSenescence Investment Memo", category: "memo", file_url: "#", file_size: 680000, company_id: "c1", uploaded_by: null, created_at: "2024-03-10" },
  { id: "doc7", title: "LunarLogistics Investment Memo", category: "memo", file_url: "#", file_size: 720000, company_id: "c4", uploaded_by: null, created_at: "2024-01-15" },
];

export const MOCK_JOBS: Job[] = [
  {
    id: "j1", company_id: "c1", title: "Senior Research Scientist - Senolytics",
    description: "Lead our senolytic drug discovery program. PhD in molecular biology or related field required.",
    location: "Basel, Switzerland", job_type: "full-time", salary_range: "CHF 120,000 - 160,000",
    referral_bonus: 5000, posted_by: null, is_active: true, created_at: "2025-03-10", updated_at: "",
    company: MOCK_COMPANIES[0],
  },
  {
    id: "j2", company_id: "c4", title: "Robotics Engineer",
    description: "Design and build autonomous robotic transfer vehicles for cislunar operations.",
    location: "Bremen, Germany", job_type: "full-time", salary_range: "EUR 85,000 - 110,000",
    referral_bonus: 3000, posted_by: null, is_active: true, created_at: "2025-03-08", updated_at: "",
    company: MOCK_COMPANIES[3],
  },
  {
    id: "j3", company_id: "c2", title: "Materials Science Intern",
    description: "Support R&D on advanced composite materials for space manufacturing.",
    location: "Toulouse, France", job_type: "internship", salary_range: "EUR 1,500/month",
    referral_bonus: 500, posted_by: null, is_active: true, created_at: "2025-03-05", updated_at: "",
    company: MOCK_COMPANIES[1],
  },
  {
    id: "j4", company_id: "c5", title: "Bioinformatics Lead",
    description: "Build and manage our computational epigenetics pipeline.",
    location: "Cambridge, UK (Hybrid)", job_type: "full-time", salary_range: "GBP 90,000 - 120,000",
    referral_bonus: 4000, posted_by: null, is_active: true, created_at: "2025-03-01", updated_at: "",
    company: MOCK_COMPANIES[4],
  },
];

export const MOCK_CIRCLES: LearningCircle[] = [
  { id: "lc1", name: "Longevity Science Deep Dive", description: "Weekly discussions on the latest longevity research papers and breakthroughs.", topic: "Longevity", max_members: 15, schedule: "Every Thursday 18:00 CET", created_by: "u5", created_at: "", updated_at: "", member_count: 8, is_member: true },
  { id: "lc2", name: "Space Economy Masterclass", description: "Learning about the commercial space industry, market dynamics, and investment opportunities.", topic: "Space", max_members: 20, schedule: "Bi-weekly Tuesday 19:00 CET", created_by: "u2", created_at: "", updated_at: "", member_count: 12, is_member: false },
  { id: "lc3", name: "VC Fundamentals for LPs", description: "Understanding venture capital mechanics, portfolio construction, and LP best practices.", topic: "Investing", max_members: 25, schedule: "Monthly, first Monday 17:00 CET", created_by: "u3", created_at: "", updated_at: "", member_count: 18, is_member: true },
];

export const MOCK_EVENTS: Event[] = [
  { id: "e1", title: "Q1 2025 LP Call", description: "Quarterly update on fund performance, portfolio updates, and Q&A with the GP team.", event_type: "lp_call", date_time: "2025-04-10T17:00:00Z", location: "Virtual (Zoom)", max_attendees: null, created_by: null, created_at: "", updated_at: "", rsvp_count: 145, user_rsvp: "attending" },
  { id: "e2", title: "NovaSenescence Demo Day", description: "Live demo of NovaSenescence Phase I results with the CEO and Chief Science Officer.", event_type: "demo", date_time: "2025-04-18T15:00:00Z", location: "Virtual (Zoom)", max_attendees: 200, created_by: null, created_at: "", updated_at: "", rsvp_count: 87, user_rsvp: undefined },
  { id: "e3", title: "Luxembourg LP Meetup", description: "In-person networking event for Luxembourg-based LPs. Drinks and light dinner provided.", event_type: "meetup", date_time: "2025-04-25T18:30:00Z", location: "Hotel Le Royal, Luxembourg City", max_attendees: 40, created_by: null, created_at: "", updated_at: "", rsvp_count: 22, user_rsvp: undefined },
  { id: "e4", title: "Space Economy Workshop", description: "Interactive workshop on understanding the space economy value chain with guest speakers from ESA.", event_type: "learning", date_time: "2025-05-05T14:00:00Z", location: "Virtual (Zoom)", max_attendees: 100, created_by: null, created_at: "", updated_at: "", rsvp_count: 34, user_rsvp: "maybe" },
];

// Dashboard summary data
export const FUND_SUMMARY = {
  totalCommitted: 30000000,
  totalDeployed: 6700000,
  deployedPercent: 22.3,
  currentNav: 8050000,
  moic: 1.4,
  irr: 18.5,
  portfolioCount: 6,
  longevityCount: 3,
  spaceCount: 3,
  userCommitted: 50000,
  userDeployedPercent: 22.3,
  userCurrentValue: 59500,
};
